### ISSUE TITLE
Get contacts

### ISSUE THREAD

**Issue by pvclever** [textmagic/textmagic-rest-cpp#3]
## method to fetch all the contacts

There are no method to fetch all the contacts
Only for id
Contacts().get(kContactId)
But likely this will be useless because you need to know Ids

I suggest implementing  new function
Contacts().getAll()

**Comment by pvclever** [comment]
## Examples for Cpp Wrapper

If you run the most examples you  get the error:  
429 \* Your rate limit is exceed. Try after 0.02 seconds \* 

Because The API has the restrictions on the frequency of requests
We have to add 1 sec delay between Api Requests

**Comment by kuzinmv** [comment]
Get all contacts quite difficult if it's about 1000000. So almost every controller has a list() method 
textmagic-rest-cpp/example/contacts.cpp:72

**Comment by kuzinmv** [comment]
I think we will add the calculation and the time delay between 2 consecutive queries in library itself, and add appropriate option in the near future. Thank you.

**Comment by pvclever** [comment]
>>>  Get all contacts quite difficult if it's about 1000000. So almost every controller has a list() method
Yes, I agree. 
But the API itself can give all contacts. Also you can set limit
GET /api/v2/contacts?page=1&limit=10&shared=0
I just notice that we do not have such possibility in c++ Wrapper (I do not insist on it)
